name: Deploy to Koyeb

on:
  push:
    branches:
      - main  # or whichever branch you want to trigger deployment from
    paths:
      - 'src/**'
      - 'package.json'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Replace with the Node version you want to use

      - name: Install dependencies
        run: npm install  # Installs dependencies from your package.json

      # If you need to build the project before deploying (e.g., for React or Vue):
      - name: Build project (optional)
        run: npm run build  # You can skip this if no build is required before starting

      # Set up Koyeb CLI
      - name: Install Koyeb CLI
        run: curl -sSL https://cli.koyeb.com/install.sh | bash  # Install Koyeb CLI

      - name: Login to Koyeb CLI
        run: koyeb login --token ${{ secrets.KOYEB_TOKEN }}  # Use GitHub Secret for security

      # Deploy using Koyeb CLI (your app is located in workspace/src)
      - name: Deploy to Koyeb
        run: |
          koyeb deploy ./workspace/src  # Deploy the app from the src folder
